### ISSUE TITLE
The 'add-path' command is deprecated and will be removed soon

### ISSUE THREAD

**Issue by NobleDraconian** [Roblox/setup-foreman#8]
Setup-foreman currently makes use of an API github provides called "add-path". This is deprecated and will be removed soon, breaking this action.
![image](https://user-images.githubusercontent.com/26460940/96176593-920efa00-0efa-11eb-832e-20e9ba4aa6fb.png)

**Comment by ZoteTheMighty** [comment]
Thanks for reporting this! I've gotten around to fixing it up, anything using `@v1` should now stop warning about this.
